export const ADD_TASK = 'ADD_TASK';

export const GET_TASKS = 'GET_TASKS';

export const POPULATE_EDIT_TASK_FORM = 'POPULATE_EDIT_TASK_FORM';

export const TOGGLE_NEW_TASK_POPUP = 'TOGGLE_NEW_TASK_POPUP';

export const TOGGLE_EDIT_TASK_POPUP = 'TOGGLE_EDIT_TASK_POPUP';

export const RESET_EDIT_TASK_STATE = 'RESET_EDIT_TASK_STATE';

export const OPEN_EDIT_TASK_POPUP = 'OPEN_EDIT_TASK_POPUP';

export const CLOSE_EDIT_TASK_POPUP = 'CLOSE_EDIT_TASK_POPUP';

export const STORE_EDIT_TASK_FORM_CHANGE = 'STORE_EDIT_TASK_FORM_CHANGE';

export const SAVE_EDITED_TASK = 'SAVE_EDITED_TASK';
