export const ADD_TASK = 'ADD_TASK';

export const GET_TASKS = 'GET_TASKS';

export const POPULATE_EDIT_TASK_FORM = 'POPULATE_EDIT_TASK_FORM';

export const TOGGLE_NEW_TASK_POPUP = 'TOGGLE_NEW_TASK_POPUP';
