export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const REMOVE_USER = 'REMOVE_USER';

export const GET_LOGIN_REGISTER_ERROR = 'GET_LOGIN_REGISTER_ERROR';

export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
