export const ADD_NEW_TASK = 'ADD_NEW_TASK';

export const GET_TASKS = 'GET_TASKS';

export const GET_USER_TASKS = 'GET_USER_TASKS';

export const GET_FILTERS = 'GET_FILTERS';

export const POPULATE_EDIT_TASK_FORM = 'POPULATE_EDIT_TASK_FORM';

export const OPEN_NEW_TASK_POPUP = 'OPEN_NEW_TASK_POPUP';

export const CLOSE_NEW_TASK_POPUP = 'CLOSE_NEW_TASK_POPUP';

export const OPEN_EDIT_TASK_POPUP = 'OPEN_EDIT_TASK_POPUP';

export const CLOSE_EDIT_TASK_POPUP = 'CLOSE_EDIT_TASK_POPUP';

export const STORE_EDIT_TASK_FORM_CHANGE = 'STORE_EDIT_TASK_FORM_CHANGE';

export const SAVE_EDITED_TASK = 'SAVE_EDITED_TASK';

export const DELETE_TASK = 'DELETE_TASK';

export const STORE_NEW_TASK_FORM_CHANGE = 'STORE_NEW_TASK_FORM_CHANGE';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const RESET_FILTERS_STORE = 'RESET_FILTERS_STORE';

export const RESET_TASKS_STORE = 'RESET_TASKS_STORE';
