export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';

export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';

export const GET_FILTERS_FAILURE = 'GET_FILTERS_FAILURE';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const RESET_FILTERS_STORE = 'RESET_FILTERS_STORE';

export const STORE_SEARCH_QUERY_INPUT = 'STORE_SEARCH_QUERY_INPUT';
