export const ADD_NEW_TASK = 'ADD_TASK';

export const GET_TASKS = 'GET_TASKS';

export const GET_FILTERS = 'GET_FILTERS';

export const POPULATE_EDIT_TASK_FORM = 'POPULATE_EDIT_TASK_FORM';

export const TOGGLE_NEW_TASK_POPUP = 'TOGGLE_NEW_TASK_POPUP';

export const RESET_NEW_TASK_STATE = 'RESET_NEW_TASK_STATE';

export const OPEN_NEW_TASK_POPUP = 'OPEN_NEW_TASK_POPUP';

export const CLOSE_NEW_TASK_POPUP = 'CLOSE_NEW_TASK_POPUP';

export const TOGGLE_EDIT_TASK_POPUP = 'TOGGLE_EDIT_TASK_POPUP';

export const RESET_EDIT_TASK_STATE = 'RESET_EDIT_TASK_STATE';

export const OPEN_EDIT_TASK_POPUP = 'OPEN_EDIT_TASK_POPUP';

export const CLOSE_EDIT_TASK_POPUP = 'CLOSE_EDIT_TASK_POPUP';

export const STORE_EDIT_TASK_FORM_CHANGE = 'STORE_EDIT_TASK_FORM_CHANGE';

export const SAVE_EDITED_TASK = 'SAVE_EDITED_TASK';

export const DELETE_TASK = 'DELETE_TASK';

export const STORE_NEW_TASK_FORM_CHANGE = 'STORE_NEW_TASK_FORM_CHANGE';
